name: jobsacademy
description: "Jobs Academy project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+6

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  webview_flutter: ^4.13.0
  # firebase configuration
  firebase_core: ^4.1.0
  firebase_messaging: ^16.0.1
  # firebase_messaging_web: ^4.0.1
  flutter_local_notifications: ^19.4.2
  shared_preferences: ^2.1.1   # Add this
  uuid: ^3.0.7                # Add this
  google_mobile_ads: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.4"
  flutter_lints: ^6.0.0


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"



flutter:

  uses-material-design: true

