// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpnkyTVh76T6aIdpi_LpxIiV47Jw9V7Hg',
    appId: '1:524525708923:web:09f0ba0e9eae09267ea4de',
    messagingSenderId: '524525708923',
    projectId: 'jobs-academy',
    authDomain: 'jobs-academy.firebaseapp.com',
    storageBucket: 'jobs-academy.firebasestorage.app',
    measurementId: 'G-11T4YEDB7B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFjgKinTG9Aq7-J7IOGSzfOVqSn2ckobM',
    appId: '1:524525708923:android:c426002cc3405f597ea4de',
    messagingSenderId: '524525708923',
    projectId: 'jobs-academy',
    storageBucket: 'jobs-academy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqXjCbozc4R5PCtjW7SNiLSeeceaKVU78',
    appId: '1:524525708923:ios:f959debe660c4e057ea4de',
    messagingSenderId: '524525708923',
    projectId: 'jobs-academy',
    storageBucket: 'jobs-academy.firebasestorage.app',
    iosBundleId: 'com.example.jobsacademy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqXjCbozc4R5PCtjW7SNiLSeeceaKVU78',
    appId: '1:524525708923:ios:f959debe660c4e057ea4de',
    messagingSenderId: '524525708923',
    projectId: 'jobs-academy',
    storageBucket: 'jobs-academy.firebasestorage.app',
    iosBundleId: 'com.example.jobsacademy',
  );
}
